### ISSUE TITLE
Tracking of fixes to synch with TS Port

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#299]
@SteinerPascal We need to do some bugfixes in Sparnatural for a client. I will use this issue to track what is fixed so you can synchronize with the TS port. It should not be anything too big.

- [x] done #301 
- [x] todo #302
- [x] already done #297 
- [x] #307 
- [ ] complicated #308 
- [x] already done #312 and latest fix of #274 
- [x] already done #319 
- [ ] linked to what pascal is doing #321 
- [x] done #322 
- [x] already done #323  
- [ ] complicated #311
- [x] #328
- [x] #329
- [ ] linked to what pascal is doing #349
- [ ] #354 width of list widget

**Comment by SteinerPascal** [comment]
Okay sure thanks!
